Add functionality for removert
sbgisen/LIO-SAM pull request #3
Opened 2023-02-13 08:48 UTC by Alpaca-zip

## Summary
このPRでは以下の機能を実装しています。
- CornerMap.pcd, GlobalMap.pcd, SurfMap.pcd, trajectory.pcd, transformations.pcdのASCIIフォーマットでの保存
- removertを利用するのに必要なoptimized_poses.txtとKeyFramePCDsフォルダの生成

<img src="https://user-images.githubusercontent.com/84959376/218403912-316663b3-c754-4895-a9ec-15bca813c4fe.png" width="300px"><img src="https://user-images.githubusercontent.com/84959376/218403976-c3b1fb9d-4a20-4cd4-8807-87e29aac52b4.png" width="300px">

## Detail
optimized_poses.txtとKeyFramePCDsフォルダを生成する場合には以下の手順を踏んでください。

1. `lio_sam/savePCD`をtrueにする。
2. `lio_sam/saveKeyframePose`をtrueにする。
3. `lio_sam/useRGB`がtrueのときは色情報付きの点群が保存されます。falseのときは色情報を含みません。

roaunchファイルのサンプルは[こちら](https://github.com/sbgisen/wheeltec_robot/blob/2f161c61a507d4765c59ededd89985d941ea0eb2/wheeltec_create_map/launch/lio_sam_slam.launch)です。

## Test
* [x] つくばチャレンジでのrosbagで動作確認

2023-02-15 00:09 UTC, Tacha-S requested changes

2023-02-15 00:09 UTC, Tacha-S commented on src/mapOptmization.cpp
> +      if(!saveKeyframePose == true)
```suggestion
      if(!saveKeyframePose)
```

2023-02-15 00:09 UTC, Tacha-S commented on src/mapOptmization.cpp
> +        if (saveKeyframePose == true)
```suggestion
        if (saveKeyframePose)
```

2023-02-15 00:38 UTC, Alpaca-zip commented
@Tacha-S 
レビュー頂きありがとうございます。修正の方は後日行わさせていただきますのでよろしくお願い致します。

2023-02-16 01:27 UTC, Alpaca-zip commented
指摘いただきました点に関して、修正いたしましたのでご確認いただけますと幸いです。よろしくお願いいたします。

2023-02-21 05:03 UTC, Tacha-S approved these changes
内容は問題なさそうですが、removertの修正と合わせて最終判断します

2023-03-07 00:10 UTC, merged