Feature/add voxel filter param
sbgisen/LIO-SAM pull request #6
Opened 2023-04-03 06:47 UTC by Alpaca-zip

## Summary
保存するpoint cloudにVoxelGridを使うか否かのパラメータ`useMappingVoxelFilter`を追加しました。

- fix #5 

## Detail
環境地図の点群密度に関わってくるVoxelGridを`useMappingVoxelFilter`によって使うか否かを条件分岐します。
- `useMappingVoxelFilter`が`true`のとき
本来のLIO-SAMと同じ処理になります。
- `useMappingVoxelFilter`が`false`のとき
  - 以下のVoxelGridを利用しません。
  https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/featureExtraction.cpp#L280
  - `saveMapService()`に渡すpoint cloudに以下のVoxelGridを適用しないように変数名を変更しています。
  https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/mapOptmization.cpp#L1077
  https://github.com/sbgisen/LIO-SAM/blob/f698fddf57684edb9a793b85548b2b603119b985/src/mapOptmization.cpp#L1082

## Test
* [x] 竹芝でのrosbagで動作確認

  

**実行方法**
- wheeltec_robotのブランチを[fix/lio_sam_args](https://github.com/sbgisen/wheeltec_robot/tree/fix/lio_sam_args)に変更してください。
- 地図を保存する際に、ファイルサイズが大きいためにSIGINTタイムアウトが発生してしまう可能性があります。これを回避するため、`--sigint-timeout`(デフォルトは15)を適宜、設定します。

rosbagから実行する場合
```
roslaunch wheeltec_bringup with_rosbag.launch
roslaunch wheeltec_create_map lio_sam_slam.launch high_density:=true --sigint-timeout=1000
rosbag play yourbag.bag --clock
```
gazeboから実行する場合
```
roslaunch wheeltec_gazebo wheeltec_gazebo.launch world_name:='$(find private_gazebo_worlds)/worlds/tsukuba_start_area.world'
roslaunch wheeltec_create_map lio_sam_slam.launch high_density:=true --sigint-timeout=1000
roslaunch wheeltec_teleop joy_control.launch
```

2023-04-03 07:34 UTC, Tacha-S requested changes

2023-04-03 07:34 UTC, Tacha-S commented on include/utility.h
> +        nh.param<bool>("lio_sam/useMappingVoxelFilter", useMappingVoxelFilter, true);
`lio_sam/downsampleRate`にあわせて
`liosam/dowmsample`とかがいいと思います。

2023-04-03 07:34 UTC, Tacha-S commented on src/mapOptmization.cpp
>          laserCloudSurfLastDSNum = laserCloudSurfLastDS->size();
ダウンサンプリングしないときに、
`laserCloudCornerLast`の点の数と`laserCloudCornerLastDSNum`が異なると思います。

また、ダウンサンプリングしないのであれば`downSizeFilterSurf.filter()`も実行する必要はないはずです。

2023-04-03 08:40 UTC, Alpaca-zip commented on src/mapOptmization.cpp
>          laserCloudSurfLastDSNum = laserCloudSurfLastDS->size();
説明足らずで申し訳ありません。
https://github.com/sbgisen/LIO-SAM/commit/e1fdee8f0e51cac0a046d4134bf0d32b88950948 の段階ではそのような形で実装をしておりましたが、地図のドリフトや自己位置が飛ぶなどの問題があったので、以下のscan2MapOptimization()内で利用するpoint cloudはダウンサンプリングされたものを利用するように変更しました。
https://github.com/sbgisen/LIO-SAM/blob/effa434ba0089cadd2407bbcb2cb037332e9032b/src/mapOptmization.cpp#L1417-L1445
恐らくですがこの問題の原因は、nearestKSearch()をする際にInputCloudとしてダウンサンプリングしているものを利用している一方で、第一引数の`pointSel`にはダウンサンプリングしていないものを利用していたことなのではないかと考えています。
https://github.com/sbgisen/LIO-SAM/blob/e1fdee8f0e51cac0a046d4134bf0d32b88950948/src/mapOptmization.cpp#L1426
https://github.com/sbgisen/LIO-SAM/blob/e1fdee8f0e51cac0a046d4134bf0d32b88950948/src/mapOptmization.cpp#L1122-L1124

こちらの問題は、`useMappingVoxelFilter`が`false`の際に、キーフレームのpoint cloudにダウンサンプリングしていないものを保存し、その他Optimization関係ではダウンサンプリングしたものを利用することで解決しました。

2023-04-03 09:12 UTC, Tacha-S commented on src/mapOptmization.cpp
>          laserCloudSurfLastDSNum = laserCloudSurfLastDS->size();
変数の意味概ね理解できました。
cornerだけを例に取りますがsurfaceも同様に読み替えてください。
`laserCloudCornerLast`と`laserCloudCornerLastDS`(DS=DownSampled)が元々存在していて、そこに`extractedCornerCloud`(extractedがあまり明確でないうえにvoxel filterでの抽出にも取れる)が追加されているのがだいぶ混同します。
どちらかというと`laserCloudCornerLast`と`laserCloudCornerLastDS`はそのままの用法で使い`OuputCornerCloud`など出力用?の変数を新しく作ったほうがわかりやすいと思います。

2023-04-03 09:33 UTC, Alpaca-zip commented on src/mapOptmization.cpp
>          laserCloudSurfLastDSNum = laserCloudSurfLastDS->size();
>  どちらかというと`laserCloudCornerLast`と`laserCloudCornerLastDS`はそのままの用法で使い`OuputCornerCloud`など出力用?の変数を新しく作ったほうがわかりやすいと思います。

確かに混乱を招くような変数名になってしまっていたと思います。こちらの件承知いたしました。

2023-04-07 03:20 UTC, Alpaca-zip commented
@Tacha-S 
以下の点を修正させていただきましたので今一度、レビューいただけますでしょうか。
- `laserCloudCornerLast`と`laserCloudCornerLastDS`は本来の用法に戻して`outputCloudCorner`という変数を新たに作りました。(Surfも同様)
- パラメータの名前を`liosam/dowmsample`に変更しました。

2023-04-07 04:31 UTC, Tacha-S approved these changes

2023-04-07 04:31 UTC, merged